// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ContosoUniversity.Models
{
    public class CourseInstructorConfiguration : IEntityTypeConfiguration<CourseInstructor>
    {
        public void Configure(EntityTypeBuilder<CourseInstructor> entity)
        {
            entity.HasKey(e => new { e.CourseID, e.InstructorID })
                .HasName("PK_dbo.CourseInstructor");

            entity.HasIndex(e => e.CourseID)
                .HasName("IX_CourseID");

            entity.HasIndex(e => e.InstructorID)
                .HasName("IX_InstructorID");

            entity.HasOne(d => d.Course)
                .WithMany(p => p.CourseInstructor)
                .HasForeignKey(d => d.CourseID)
                .HasConstraintName("FK_dbo.CourseInstructor_dbo.Course_CourseID");

            entity.HasOne(d => d.Instructor)
                .WithMany(p => p.CourseInstructor)
                .HasForeignKey(d => d.InstructorID)
                .HasConstraintName("FK_dbo.CourseInstructor_dbo.Instructor_InstructorID");
        }
    }
}
