// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ContosoUniversity.Models
{
    public class DepartmentConfiguration : IEntityTypeConfiguration<Department>
    {
        public void Configure(EntityTypeBuilder<Department> entity)
        {
            entity.HasIndex(e => e.InstructorID)
                .HasName("IX_InstructorID");

            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();

            entity.HasOne(d => d.Instructor)
                .WithMany(p => p.Department)
                .HasForeignKey(d => d.InstructorID)
                .HasConstraintName("FK_dbo.Department_dbo.Instructor_InstructorID");
        }
    }
}
