// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ContosoUniversity.Models
{
    public class EnrollmentConfiguration : IEntityTypeConfiguration<Enrollment>
    {
        public void Configure(EntityTypeBuilder<Enrollment> entity)
        {
            entity.HasIndex(e => e.CourseID)
                .HasName("IX_CourseID");

            entity.HasIndex(e => e.StudentID)
                .HasName("IX_StudentID");

            entity.HasOne(d => d.Course)
                .WithMany(p => p.Enrollment)
                .HasForeignKey(d => d.CourseID)
                .HasConstraintName("FK_dbo.Enrollment_dbo.Course_CourseID");

            entity.HasOne(d => d.Student)
                .WithMany(p => p.Enrollment)
                .HasForeignKey(d => d.StudentID)
                .HasConstraintName("FK_dbo.Enrollment_dbo.Person_StudentID");
        }
    }
}
