// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ContosoUniversity.Models
{
    public class OfficeAssignmentConfiguration : IEntityTypeConfiguration<OfficeAssignment>
    {
        public void Configure(EntityTypeBuilder<OfficeAssignment> entity)
        {
            entity.HasKey(e => e.InstructorID)
                .HasName("PK_dbo.OfficeAssignment");

            entity.HasIndex(e => e.InstructorID)
                .HasName("IX_InstructorID");

            entity.Property(e => e.InstructorID).ValueGeneratedNever();

            entity.HasOne(d => d.Instructor)
                .WithOne(p => p.OfficeAssignment)
                .HasForeignKey<OfficeAssignment>(d => d.InstructorID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.OfficeAssignment_dbo.Instructor_InstructorID");
        }
    }
}
