// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ContosoUniversity.Models
{
    public class vwCourseStudentsConfiguration : IEntityTypeConfiguration<vwCourseStudents>
    {
        public void Configure(EntityTypeBuilder<vwCourseStudents> entity)
        {
            entity.HasNoKey();

            entity.ToView("vwCourseStudents");
        }
    }
}
