// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ContosoUniversity.Models
{
    public class vwCourseStudentCountConfiguration : IEntityTypeConfiguration<vwCourseStudentCount>
    {
        public void Configure(EntityTypeBuilder<vwCourseStudentCount> entity)
        {
            entity.HasNoKey();

            entity.ToView("vwCourseStudentCount");
        }
    }
}
